---
- name: Installing advanced tools
  hosts: comp
  become: true

  tasks:

    - name: git clone artillery
      git:
        repo: https://github.com/BinaryDefense/artillery.git
        dest: /opt/.artillery

    - name: git clone kn1gh7
      git:
        repo: https://github.com/spinjrock/kn1gh7.git
        dest: /opt/.kn1gh7
    
    - name: Installing kn1gh7 dependencies on debian systems
      apt:
        pkg:
        - python3
        - python3-audit
        - auditd
        - audispd-plugins
        state: latest
        update-cache: yes
      when: ansible_os_family == "Debian"
    
    - name: Installing kn1gh7 dependencies on RedHat based systems
      dnf:
        pkg:
        - python3
        - python3-audit
        - audit
        - audispd-plugins
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Aquire the drip
      get_url:
        url: https://pastebin.com/raw/6g578MpH
        dest: /opt/.drip_goku.txt
        mode: 0600

    - name: Fat yoshi time
      get_url:
        url: https://pastebin.com/raw/Zunkgn7G
        dest: /opt/.fat_yoshi.txt
        mode: 0600

    - name: Amogus
      get_url:
        url: https://pastebin.com/raw/yAn1gw53
        dest: /opt/.jerma_sus.txt
        mode: 0600
